import { CapabilityGroup, ExperienceEntry, Navbar, ProcessStep, ProjectRow, SectionHeading } from "@/components/portfolio";

const projects = [
  ["01", "Certificate Lifecycle Management", "Digital Trust / PKI", "Certificate lifecycle management across implementation, integration, workflow validation and deployment support.", "Implementation, configuration, workflow validation and deployment support.", ["PKI", "CLM", "REST API", "SSL/TLS"], "/projects/certificate-lifecycle-management"],
  ["02", "S/MIME Integration", "Digital Trust / Email Security", "Enterprise S/MIME certificate enrollment and workflow support for subscriber onboarding, verification and lifecycle activities.", "Enrollment workflows, verification, API integration and lifecycle activities.", ["S/MIME", "PKI", "X.509", "API"], "/projects/smime-integration"],
  ["03", "Certificate Authority API Integration", "API Integration / PKI", "REST and SOAP API testing for certificate ordering, retrieval, verification, renewal, reissue and revocation.", "Authentication, request validation, lifecycle testing and technical troubleshooting.", ["REST", "SOAP", "OAuth 2.0", "Postman"], "/projects/ca-api-integration"],
  ["04", "Enterprise System Integration", "Project Engineering", "End-to-end enterprise implementation spanning requirements, integration, testing, troubleshooting and deployment.", "Requirements, documentation, stakeholder coordination, SIT, UAT and deployment support.", ["API", "SIT", "UAT", "Business Analysis"], "/projects/enterprise-system-integration"],
] as const;

export default function Home() {
  return <main><Navbar />
    <section className="relative overflow-hidden bg-white px-6 py-28 lg:px-8 lg:py-38"><div className="grid-fade absolute inset-0 opacity-70"/><div className="relative mx-auto max-w-6xl"><p className="eyebrow text-xs font-bold uppercase text-blue-700">Product Engineer · Digital Trust · Enterprise Integration</p><h1 className="mt-7 max-w-5xl text-5xl font-bold leading-[.98] tracking-[-.07em] text-slate-950 md:text-7xl lg:text-8xl">I help organizations implement and integrate digital trust technologies and enterprise systems.</h1><p className="mt-8 max-w-2xl text-lg leading-8 text-slate-600">Focused on product implementation, PKI, certificate management, API integration and technical validation.</p><div className="mt-10 flex flex-wrap gap-4"><a href="#work" className="rounded-full bg-blue-700 px-6 py-3.5 text-sm font-bold text-white transition hover:bg-slate-950">Explore My Work</a><a href="mailto:fiqtau8@gmail.com" className="rounded-full border border-slate-300 bg-white px-6 py-3.5 text-sm font-bold text-slate-800 transition hover:border-blue-700">Let&apos;s Talk</a><a href="https://www.linkedin.com/in/taufiqramlan" target="_blank" rel="noreferrer" className="py-3.5 text-sm font-bold text-slate-700 underline underline-offset-4 hover:text-blue-700">LinkedIn ↗</a></div></div></section>
    <section id="services" className="px-6 py-24 lg:px-8"><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading eyebrow="What I can help with" title="From technical requirements to a workable solution." text="Practical support across digital trust, integration, implementation and enterprise technology."/><div><CapabilityGroup number="01" title="Digital Trust" items={["PKI", "SSL/TLS", "S/MIME", "Certificate Lifecycle Management", "Digital Certificates"]}/><CapabilityGroup number="02" title="System & API Integration" items={["REST API", "SOAP API", "Certificate Authority integration", "Enterprise system integration", "API testing and troubleshooting"]}/><CapabilityGroup number="03" title="Product Implementation" items={["Requirement analysis", "Product configuration", "SIT", "UAT", "Deployment support", "Customer training", "Technical documentation"]}/><CapabilityGroup number="04" title="Enterprise Technology" items={["Active Directory", "Linux", "Windows Server", "VMware", "DNS", "Infrastructure troubleshooting"]}/></div></div></section>
    <section id="work" className="bg-white px-6 py-24 lg:px-8"><div className="mx-auto max-w-6xl"><SectionHeading eyebrow="Selected work" title="Work grounded in real implementation and integration." text="Selected case studies across digital trust, PKI, APIs and enterprise delivery."/><div className="mt-14">{projects.map(([number,title,category,description,work,technologies,href]) => <ProjectRow key={number} number={number} title={title} category={category} description={description} work={work} technologies={[...technologies]} href={href}/>)}</div></div></section>
    <section id="approach" className="bg-slate-950 px-6 py-24 lg:px-8"><div className="mx-auto max-w-6xl"><div className="max-w-2xl"><p className="eyebrow text-xs font-bold uppercase text-blue-400">How I work</p><h2 className="mt-4 text-3xl font-bold tracking-[-.05em] text-white md:text-5xl">A structured path from requirements to delivery.</h2></div><div className="mt-14 grid gap-x-8 md:grid-cols-2 lg:grid-cols-5"><ProcessStep number="01" title="Understand" text="Understand business requirements, technical requirements and the existing environment."/><ProcessStep number="02" title="Design" text="Define the integration, workflow and technical approach."/><ProcessStep number="03" title="Implement" text="Configure the solution, integrate systems and perform testing."/><ProcessStep number="04" title="Validate" text="SIT, UAT and troubleshooting to validate the workflow."/><ProcessStep number="05" title="Deploy" text="Deployment support, documentation and knowledge transfer."/></div></div></section>
    <section className="px-6 py-24 lg:px-8"><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading eyebrow="Technical capabilities" title="A focused, practical toolkit."/><div className="space-y-7 text-lg leading-8"><p><b>Digital Trust</b><br/>PKI · SSL/TLS · S/MIME · CLM</p><p><b>Integration</b><br/>REST · SOAP · Certificate Authority APIs · Enterprise Systems</p><p><b>Identity & Infrastructure</b><br/>Active Directory · Linux · Windows Server · VMware · DNS</p><p><b>Delivery</b><br/>Configuration · SIT · UAT · Documentation · Training</p></div></div></section>
    <section id="experience" className="bg-white px-6 py-24 lg:px-8"><div className="mx-auto max-w-6xl"><SectionHeading eyebrow="Experience" title="Experience across product, integration and infrastructure."/><div className="mt-14"><ExperienceEntry title="Product Engineer" company="MSC Trustgate.com Sdn Bhd" text="Supports implementation, integration and deployment of digital trust solutions across customer, development, PKI, DevOps and system-analysis teams." areas={["Product Engineering", "Digital Trust", "Integration", "Implementation", "Testing"]}/><ExperienceEntry title="Project Engineer" company="Gross Synergy Sdn Bhd" text="Led and supported enterprise implementation projects involving system integration, APIs, e-commerce platforms and business workflows." areas={["Requirements", "SIT", "UAT", "Troubleshooting", "Project Coordination"]}/><ExperienceEntry title="Network Engineer" company="REDtone Engineering and Network Services Sdn Bhd" text="Supported server infrastructure, network monitoring, enterprise IT operations and user support activities." areas={["VMware", "Network Monitoring", "DNS", "Active Directory"]}/><ExperienceEntry title="IT Trainee" company="Agensi Kaunseling dan Pengurusan Kredit (AKPK)" text="Gained practical exposure to enterprise IT operations, technical support and organisational IT processes." areas={["IT Operations", "Technical Support"]}/></div></div></section>
    <section className="px-6 py-24 lg:px-8"><div className="mx-auto grid max-w-6xl gap-14 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading eyebrow="About" title="Technology, product, integration and customer requirements."/><p className="text-lg leading-8 text-slate-600">I&apos;m Muhammad Taufiq, a Product Engineer working across digital trust, product implementation and enterprise integration. I help translate requirements into practical workflows, support technical validation, and connect product and customer teams through delivery.</p></div></section>
    <section className="bg-white px-6 py-24 lg:px-8"><div className="mx-auto max-w-6xl"><SectionHeading eyebrow="Selected certifications" title="Continuous technical development."/><div className="mt-12 grid gap-6 md:grid-cols-3"><p className="border-t border-slate-300 pt-5 font-semibold">Microsoft Azure Fundamentals<br/><span className="mt-2 block text-sm font-normal text-slate-600">Microsoft / APU Certified Cloud Administrator</span></p><p className="border-t border-slate-300 pt-5 font-semibold">Microsoft Azure Administrator<br/><span className="mt-2 block text-sm font-normal text-slate-600">AZ-104 Training</span></p><p className="border-t border-slate-300 pt-5 font-semibold">Linux for Web Server<br/><span className="mt-2 block text-sm font-normal text-slate-600">Training.My</span></p></div></div></section>
    <section id="contact" className="bg-blue-700 px-6 py-24 text-white lg:px-8"><div className="mx-auto max-w-6xl"><p className="eyebrow text-xs font-bold uppercase text-blue-100">Contact</p><h2 className="mt-5 max-w-3xl text-4xl font-bold tracking-[-.05em] md:text-6xl">Working on a digital trust or enterprise integration project?</h2><p className="mt-6 max-w-2xl text-lg leading-8 text-blue-100">I can help with solution analysis, API integration, product implementation and technical validation.</p><div className="mt-10 flex flex-wrap gap-4"><a href="mailto:fiqtau8@gmail.com" className="rounded-full bg-white px-6 py-3.5 text-sm font-bold text-blue-800">Let&apos;s Talk</a><a href="https://www.linkedin.com/in/taufiqramlan" target="_blank" rel="noreferrer" className="rounded-full border border-white/40 px-6 py-3.5 text-sm font-bold text-white">LinkedIn</a></div></div></section>
    <footer className="bg-slate-950 px-6 py-7 text-sm text-slate-400 lg:px-8"><div className="mx-auto flex max-w-6xl justify-between gap-3"><span>© 2026 Muhammad Taufiq</span><span>Product Engineer</span></div></footer>
  </main>;
}
