import Link from "next/link";

export function Navbar() {
  return <header className="sticky top-0 z-50 border-b border-slate-200/80 bg-[#fafafa]/90 backdrop-blur"><div className="mx-auto flex h-18 max-w-6xl items-center justify-between px-6 lg:px-8"><Link href="/" className="text-lg font-bold tracking-[-.05em] text-slate-950">TAUFIQ<span className="text-blue-600">.</span></Link><nav className="hidden gap-6 text-sm font-medium text-slate-600 md:flex"><Link href="/#services">Services</Link><Link href="/#work">Work</Link><Link href="/#approach">Approach</Link><Link href="/#experience">Experience</Link><Link href="/#contact">Contact</Link></nav><a href="mailto:fiqtau8@gmail.com" className="rounded-full bg-slate-950 px-4 py-2 text-sm font-semibold text-white transition hover:bg-blue-700">Let&apos;s Talk</a></div></header>;
}

export function SectionHeading({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) {
  return <div className="max-w-2xl"><p className="eyebrow text-xs font-bold uppercase text-blue-700">{eyebrow}</p><h2 className="mt-4 text-3xl font-bold tracking-[-.05em] text-slate-950 md:text-5xl">{title}</h2>{text && <p className="mt-5 text-lg leading-8 text-slate-600">{text}</p>}</div>;
}

export function CapabilityGroup({ number, title, items }: { number: string; title: string; items: string[] }) {
  return <div className="border-t border-slate-300 py-7"><div className="flex gap-6"><span className="pt-1 text-xs font-bold text-blue-700">{number}</span><div><h3 className="text-xl font-bold text-slate-950">{title}</h3><p className="mt-3 leading-7 text-slate-600">{items.join(" · ")}</p></div></div></div>;
}

export function ProjectRow({ number, title, category, description, work, technologies, href }: { number: string; title: string; category: string; description: string; work: string; technologies: string[]; href: string }) {
  return <article className="group grid gap-6 border-t border-slate-300 py-9 md:grid-cols-[80px_1fr_220px] md:gap-10"><span className="text-sm font-bold text-blue-700">{number}</span><div><p className="eyebrow text-[11px] font-bold uppercase text-slate-500">{category}</p><h3 className="mt-3 text-2xl font-bold tracking-[-.04em] text-slate-950 md:text-3xl">{title}</h3><p className="mt-4 max-w-2xl leading-7 text-slate-600">{description}</p><p className="mt-4 text-sm leading-6 text-slate-700"><span className="font-bold">What I worked on: </span>{work}</p><div className="mt-5 flex flex-wrap gap-x-3 gap-y-1 text-xs font-semibold uppercase tracking-wide text-blue-700">{technologies.map((item) => <span key={item}>{item}</span>)}</div></div><div className="md:flex md:items-end"><Link href={href} className="inline-flex border-b border-slate-950 pb-1 text-sm font-bold text-slate-950 transition group-hover:border-blue-600 group-hover:text-blue-700">View case study <span className="ml-2">→</span></Link></div></article>;
}

export function ProcessStep({ number, title, text }: { number: string; title: string; text: string }) {
  return <div className="border-t border-slate-700 py-6"><span className="text-xs font-bold text-blue-400">{number}</span><h3 className="mt-4 text-xl font-bold text-white">{title}</h3><p className="mt-3 leading-7 text-slate-400">{text}</p></div>;
}

export function ExperienceEntry({ title, company, text, areas }: { title: string; company: string; text: string; areas: string[] }) {
  return <article className="grid gap-5 border-t border-slate-300 py-8 md:grid-cols-[1fr_1.4fr]"><div><h3 className="text-xl font-bold text-slate-950">{title}</h3><p className="mt-1 font-medium text-slate-600">{company}</p></div><div><p className="leading-7 text-slate-600">{text}</p><p className="mt-4 text-sm font-semibold text-blue-700">{areas.join(" · ")}</p></div></article>;
}

export type CaseStudy = { number: string; title: string; category: string; intro: string; overview: string; contribution: string[]; value: string; technologies: string[] };
export function CaseStudyPage({ study }: { study: CaseStudy }) {
  return <main className="min-h-screen bg-[#fafafa]"><header className="border-b border-slate-200 bg-white"><div className="mx-auto flex h-18 max-w-6xl items-center justify-between px-6 lg:px-8"><Link href="/" className="text-lg font-bold tracking-[-.05em] text-slate-950">TAUFIQ<span className="text-blue-600">.</span></Link><Link href="/#work" className="text-sm font-semibold text-slate-600 transition hover:text-blue-700">← Back to work</Link></div></header><section className="border-b border-slate-200 bg-white px-6 py-20 lg:px-8 lg:py-28"><div className="mx-auto max-w-6xl"><p className="eyebrow text-xs font-bold uppercase text-blue-700">Case study {study.number} · {study.category}</p><h1 className="mt-6 max-w-4xl text-5xl font-bold tracking-[-.06em] text-slate-950 md:text-7xl">{study.title}</h1><p className="mt-7 max-w-2xl text-xl leading-9 text-slate-600">{study.intro}</p></div></section><section className="px-6 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading eyebrow="Overview" title="The work in context."/><p className="text-lg leading-8 text-slate-600">{study.overview}</p></div></section><section className="border-y border-slate-200 bg-white px-6 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading eyebrow="Contribution" title="What I worked on."/><ul className="space-y-3">{study.contribution.map((item) => <li key={item} className="border-b border-slate-200 pb-3 leading-7 text-slate-700">{item}</li>)}</ul></div></section><section className="px-6 py-20 lg:px-8"><div className="mx-auto grid max-w-6xl gap-12 lg:grid-cols-[.75fr_1.25fr]"><SectionHeading eyebrow="Business value" title="A practical implementation focus."/><div><p className="text-lg leading-8 text-slate-600">{study.value}</p><div className="mt-8 flex flex-wrap gap-2">{study.technologies.map((item) => <span key={item} className="rounded-full bg-blue-50 px-4 py-2 text-sm font-semibold text-blue-800">{item}</span>)}</div></div></div></section><section className="bg-slate-950 px-6 py-16 text-white lg:px-8"><div className="mx-auto flex max-w-6xl flex-col justify-between gap-6 md:flex-row md:items-center"><div><p className="eyebrow text-xs font-bold uppercase text-blue-400">Let&apos;s talk</p><h2 className="mt-3 text-3xl font-bold tracking-[-.04em]">Working on an integration project?</h2></div><a href="mailto:fiqtau8@gmail.com" className="w-fit rounded-full bg-white px-6 py-3 text-sm font-bold text-slate-950">Get in touch</a></div></section></main>;
}
